const dish = [
  {
    name:"Cucumber Tomato Avocado Salad",
    image: "./photos/cucumber-tomato-avocado-salad.webp",
    cal: 180,
    unit: "g",
    base: 150,
    stepup: 75,
    stepdown: 25,
    minimum: 0,
    maximum: 600,
},
{
  name:"Creamy Lemon Chicken",
  image:"./photos/creamy-lemon-chicken.webp",
  cal:120,
  unit:"g",
  base:150,
  stepup:75,
  stepdown:25,
  minimum:0,
  maximum:600,
},
{
  name:"Grilled Shrimp Tacos",
  image:"./photos/grilled-shrimp-tacos.webp",
  cal:120,
  unit:"g",
  base:150,
  stepup:75,
  stepdown:25,
  minimum:0,
  maximum:600,
},
{
  name:"Honey BBQ Chicken Wings",
  image:"./photos/honey-bbq-chicken-wings.webp",
  cal:120,
  unit:"g",
  base:150,
  stepup:75,
  stepdown:25,
  minimum:0,
  maximum:600,
},
{
  name:"Ingredient Dough Pizza",
  image:"./photos/ingredient-dough-pizza.webp",
  cal:120,
  unit:"g",
  base:150,
  stepup:75,
  stepdown:25,
  minimum:0,
  maximum:600,
},
{
  name:"Beef and Broccoli Noodle Stir Fry",
  image:"./photos/beef-and-broccoli-noodle-stir-fry.webp",
  cal:120,
  unit:"g",
  base:150,
  stepup:75,
  stepdown:25,
  minimum:0,
  maximum:600,
},
{
  name:"Chinese Chicken Fried Rice",
  image:"./photos/chinese-chicken-fried-rice.webp",
  cal:120,
  unit:"g",
  base:150,
  stepup:75,
  stepdown:25,
  minimum:0,
  maximum:600,
},
{
  name:"Classic Chicken Noodle Soup",
  image:"./photos/classic-chicken-noodle-soup.webp",
  cal:120,
  unit:"g",
  base:150,
  stepup:75,
  stepdown:25,
  minimum:0,
  maximum:600,
},
{
  name:"Fivecheese Mac and Cheese",
  image:"./photos/fivecheese-mac-and-cheese.webp",
  cal:120,
  unit:"g",
  base:150,
  stepup:75,
  stepdown:25,
  minimum:0,
  maximum:600,
},
{
  name:"Grilled Cheese",
  image:"./photos/grilled-cheese.webp",
  cal:120,
  unit:"g",
  base:150,
  stepup:75,
  stepdown:25,
  minimum:0,
  maximum:600,
},
{
  name:"Mushroom Stroganoff",
  image:"./photos/mushroom-stroganoff.webp",
  cal:120,
  unit:"g",
  base:150,
  stepup:75,
  stepdown:25,
  minimum:0,
  maximum:600,
},
{
  name:"Scalloped Potatoes",
  image:"./photos/scalloped-potatoes.webp",
  cal:120,
  unit:"g",
  base:150,
  stepup:75,
  stepdown:25,
  minimum:0,
  maximum:600,
},
]